import os
import json
import glob
import requests
import subprocess
from pathlib import Path

# --- Configuration ---
VARIANTS_DIR = "variants_output"
SEEDS_DIR = "toxin_seeds"
OUTPUT_PDB_DIR = "variants_predicted_pdbs"
TM_SCORE_FILE = "tm_scores.json"
# Ensure you have TMalign installed (brew install tm-align or conda install tmalign)
TMALIGN_BIN = "TMalign" 

def get_esmfold_structure(sequence, name):
    """Predicts 3D structure using the ESMFold API."""
    print(f"  → Folding {name}...")
    url = "https://api.esmatlas.com/foldSequence/v1/pdb/"
    response = requests.post(url, data=sequence)
    if response.status_code == 200:
        return response.text
    else:
        print(f"    Error folding {name}: {response.status_code}")
        return None

def run_tm_align(predict_pdb, native_pdb):
    """Runs TMalign and parses the TM-score (normalized by native chain)."""
    try:
        result = subprocess.run(
            [TMALIGN_BIN, predict_pdb, native_pdb],
            capture_output=True, text=True, check=True
        )
        # Parse the TM-score (usually the line starting with "TM-score= ... (if normalized by chain 2)")
        for line in result.stdout.split('\n'):
            if "TM-score=" in line and "Chain_2" in line:
                return float(line.split()[1])
    except Exception as e:
        print(f"    Alignment error: {e}")
        return 0.0
    return 0.0

def main():
    os.makedirs(OUTPUT_PDB_DIR, exist_ok=True)
    tm_results = {}

    # 1. Identify all stealth fastas generated by MPNN
    variant_files = glob.glob(f"{VARIANTS_DIR}/**/stealth/*.fa") + \
                    glob.glob(f"{VARIANTS_DIR}/**/stealth/*.fasta")

    for v_file in variant_files:
        # Extract toxin type (e.g., ricin_A_chain) from path
        toxin_id = Path(v_file).parts[1]
        native_pdb = os.path.join(SEEDS_DIR, f"{toxin_id}.pdb")
        
        if not os.path.exists(native_pdb):
            print(f"⚠️ Native PDB not found for {toxin_id}, skipping alignment.")
            continue

        # Parse sequences from the variant fasta
        with open(v_file, 'r') as f:
            lines = f.readlines()
            
        current_id = ""
        for line in lines:
            if line.startswith(">"):
                current_id = line.strip().lstrip(">").replace("/", "_")
            else:
                seq = line.strip()
                pdb_path = os.path.join(OUTPUT_PDB_DIR, f"{current_id}.pdb")
                
                # Fold if not already cached
                if not os.path.exists(pdb_path):
                    pdb_content = get_esmfold_structure(seq, current_id)
                    if pdb_content:
                        with open(pdb_path, "w") as out_f:
                            out_f.write(pdb_content)
                
                # Align and get TM-score
                if os.path.exists(pdb_path):
                    score = run_tm_align(pdb_path, native_pdb)
                    print(f"    TM-score vs {toxin_id}: {score:.4f}")
                    
                    tm_results[current_id] = {
                        "tm_score": score,
                        "toxin_type": toxin_id,
                        "sequence_identity_pct": 0.0 # Will be updated by evasion script or BLAST
                    }

    # 2. Save results
    with open(TM_SCORE_FILE, "w") as f:
        json.dump(tm_results, f, indent=4)
    print(f"\n✅ Structural validation complete. Results saved to {TM_SCORE_FILE}")

if __name__ == "__main__":
    main()